MovieShop/MovieShopMVC/Controllers/AccountController.cs
using ApplicationCore.Contracts.Services;
using ApplicationCore.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace MovieShopMVC.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAccountService _accountService;

        public AccountController(IAccountService accountService)
        {
            _accountService = accountService;
        }

        [HttpGet]
        public async Task<IActionResult> Login()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Login(LoginModel model)
        {
            var user = await _accountService.ValidateUser(model.Email, model.Password);
            var claims = new List<Claim>()
            {
                new Claim(ClaimTypes.Email, user.Email),
                new Claim(ClaimTypes.GivenName, user.FirstName),
                new Claim(ClaimTypes.Surname, user.LastName),
                new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                new Claim(ClaimTypes.DateOfBirth, user.DateOfBirth.ToShortDateString())
                // new Claim("Language", "English")
            };
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity));
            return LocalRedirect("~/");
        }

        [HttpGet]
        public async Task<IActionResult> Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var user = await _accountService.RegisterUser(model);
            return RedirectToAction("Login");
        }
        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return LocalRedirect("~/");
        }
    }
}

MovieShop/MovieShopMVC/Controllers/MoviesController.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;

        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        public async Task<IActionResult> Details(int id) //http://movieshop.com/movies/details/1  // int 改成 Task<int>, void 改成 Task
        {
            var movieDetails = await _movieService.GetMovieDetails(id);

            return View(movieDetails);
        }

        public async Task<IActionResult> Genres(int id, int pageSize = 30, int pageNumber = 1)
        {
            var pagedMovies = await _movieService.GetMoviesByGenrePagination(id, pageSize, pageNumber);
            return View(pagedMovies);
        }
    }
}

MovieShop/MovieShopMVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace MovieShopMVC.Controllers
{
    [Authorize]

    public class UserController : Controller
    {
        [HttpGet]
        //[Authorize]
        public async Task<IActionResult> Purchase()
        {
            //var isLoggedIn = this.HttpContext.User.Identity.IsAuthenticated;
            //if(!isLoggedIn)
            //{
            //    return RedirectToAction("Login", "Account");
            //}
            //else
            //{
            //    var userId = Convert.ToInt32(this.HttpContext.User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value);
            //}
            //// Get purchased movies by userId and pass to view
            var userId = Convert.ToInt32(this.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            return View(); 
        }

        [HttpGet]
        //[Authorize]

        public async Task<IActionResult> Favorite()
        {
            var userId = Convert.ToInt32(this.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);

            return View();
        }

        [HttpGet]

        public async Task<IActionResult> Reviews()
        {
            var userId = Convert.ToInt32(this.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);

            return View();
        }
    }
}

MovieShop/MovieShopMVC/Views/Movies/Details.cshtml
@model ApplicationCore.Models.MovieDetailModel;

<h1>@Model.Title</h1>

<h1>@Model.Overview</h1>

<h2>Average Rating: @Model.AverageRating</h2>

<h3>Cast</h3>
<ul>
    @foreach (var cast in Model.Casts)
    {
        <li>
            <img src="@cast.ProfilePath" alt="@cast.Name" width="100" />
            <strong>@cast.Name</strong> as <em>@cast.Character</em>
        </li>
    }
</ul>

<h3>Trailers</h3>
<ul>
    @foreach (var trailer in Model.Trailers)
    {
        <li>
            <a href="@trailer.TrailerUrl" target="_blank">@trailer.Name</a>
        </li>
    }
</ul>

MovieShop/MovieShopMVC/Views/Movies/Genres.cshtml
@model ApplicationCore.Models.PagedResultSet<ApplicationCore.Models.MovieCard>

@{
    int totalPage = Model.TotalPages;
    int curIndex = Model.PageIndex;
    bool hasPrev = Model.HasPreviousPage;
    bool hasNext = Model.HasNextPage;
}

<div class="rounded">
    <div class="container-fluid">
        <div class="row">
            @foreach (var movie in Model.Data)
            {
                <div class="col-6 col-sm-4 col-md-3 col-xl-2">
                    <partial name="_MovieCard" model="movie" />

                </div>
            }

        </div>

    </div>

</div>

<nav aria-label="Page navigation example">
    <ul class="pagination">
        
        @if (hasPrev)
        {
            <li class="page-item"><a class="page-link" asp-route-pageNumber="@(Math.Max(1, curIndex - 1))">Previous</a></li>
        }
        else
        {
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        }
        @for (int i = Math.Max(1, curIndex - 1); i <= Math.Min(curIndex + 1, totalPage); i++)
        {
            <li class="page-item">
                <a class="page-link" asp-route-pageNumber="@i">@i</a>
            </li>
        }
        @if (hasNext)
        {
            <li class="page-item"><a class="page-link" asp-route-pageNumber="@(Math.Min(curIndex + 1, totalPage))">Next</a></li>
        }
        else
        {
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>

        }
    </ul>
</nav>

MovieShop/MovieShopMVC/Views/Shared/_LoginInfo.cshtml
@using MovieShopMVC.Services
@inject ICurrentUser currentUser

@if (!currentUser.IsAuthenticated)
{
    <div class="text-end d-flex justify-content-end gap-2">
        <a class="btn btn-outline-primary" asp-controller="Account" asp-action="Login">Login</a>
        <a class="btn btn-outline-primary" asp-controller="Account" asp-action="Register">Register</a>
    </div>
}
else
{
    <div class="text-end">
        <ul class="nav">
            <li class="nav-item dropdown text-capitalize">
                <a class="nav-item dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    @currentUser.FullName
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li><a class="dropdown-item" asp-controller="User" asp-action="Purchases">Library</a></li>
                    <li><a class="dropdown-item" asp-controller="User" asp-action="Favorites">Favorites</a></li>
                    <li><a class="dropdown-item" asp-controller="Account" asp-action="Profile">Account</a></li>
                    <li><a class="dropdown-item" asp-controller="Account" asp-action="Logout">Logout</a></li>

                </ul>
            </li>
        </ul>
    </div>
}
)

MovieShop/MovieShopMVC/Views/Shared/_MovieCard.cshtml
@model ApplicationCore.Models.MovieCard

<div class="card mb-4">
    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id">
        <img src="@Model.PosterUrl" alt="@Model.Title" class="img-fluid" />
    </a>
</div>